title: 李智维 | Zhiwei Li
email: lzwjava@gmail.com
description: >-
  truth freedom love
baseurl: ""
url: "https://lzwjava.github.io"

tagline: truth freedom love

author:
  name: Zhiwei Li
  twitter: lzwjava

twitter:
  username: lzwjava
  card: summary_large_image

social:
  name: Zhiwei Li
  links:
    - https://twitter.com/lzwjava
    - https://weibo.com/zhiweilee
    - https://github.com/lzwjava
    - https://www.zhihu.com/people/lzwjava

theme: jekyll-theme-cayman

google_analytics: "UA-66656236-1"

permalink: /:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - sync_*
  - Gemfile
  - Gemfile.lock
  - README.md

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

ssl_certificate: false
