title: Zhiwei Li
email: lzwjava@gmail.com
description: >-
  李智维
baseurl: ""
url: "https://lzwjava.github.io"

tagline: truth freedom

author:
  name: Zhiwei Li
  twitter: lzwjava

twitter:
  username: lzwjava
  card: summary_large_image

social:
  name: Zhiwei Li
  links:
    - https://twitter.com/lzwjava
    - https://weibo.com/zhiweilee
    - https://github.com/lzwjava
    - https://www.zhihu.com/people/lzwjava

theme: jekyll-theme-cayman

google_analytics: "UA-66656236-1"

permalink: /:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - wandb
  - scripts
  - pelican
  - test
  - clash.log
  - c
  - cpp
  - rust
  - logs
  - invoice
  - Makefile
  - Dockerfile
  - requirements
  - original
  - feeds
  - backup
  - prompt_md
  - text_test
  - tmp
  - blog-server
  - latex
  - excluded_notes
  - gcm-diagnose.log
  - AGENTS.md

markdown: kramdown

kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge

ssl_certificate: false

timezone: Asia/Shanghai

starting_year: 1995

release: 9f2543e067d3c64f041149a90e8c0d46996dc396
