name: Transate notes

on:
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          pip install -r requirements/requirements.txt

      - name: Translate notes
        run: |
          python scripts/translation/update_lang.py --file original/2025-01-11-notes-en.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/**/*.md
          git diff --cached --quiet || git commit -m "Add translated notes"
          git push
