name: Update NYTimes Articles

on:
  # schedule:
  #   - cron: '30 16 * * 0' 
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  #   paths:
  #     - 'scripts/nytimes/nytimes.py'
  #     - '.github/workflows/nytimes.yml'

concurrency:
  group: 'nytimes'
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  update_nytimes:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"  

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.simple.txt

      - name: Run NYTimes Script
        id: nytimes_update
        run: python -m scripts.nytimes.nytimes
        continue-on-error: true

      - name: Commit NYTimes Changes
        if: steps.nytimes_update.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add notes/2025-03-14-nytimes-en.md
          git diff --cached --quiet || git commit -m "chore(nytimes): Update NYTimes links"
          git push || {
            echo "Push failed, attempting pull and merge"
            git pull --rebase
            git push
          }

      - name: Trigger Workflow gh-pages
        if: steps.nytimes_update.outcome == 'success'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/lzwjava/lzwjava.github.io/actions/workflows/gh-pages.yml/dispatches \
            -d '{"ref": "main"}'
